[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
email_address = "0.2.4"
http = "1.1.0"
serde = "1"
serde_json = "1.0.114"
sqlx = { version = "0.8.2", optional = true }

[features]
sqlx = ["dep:sqlx"]
